import Head from "next/head";
import styles from '../../styles/css/buscadorIngrediente.module.css'

export default function BuscadorAlimentos() {

    return (
        <section className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta property="og:image" content="https://buscadog.manu-scholz.com/wp-content/uploads/2022/05/test1.jpg" />
            </Head>

            <div className={styles.inputContainer}>
                <h1>Sección en construcción...</h1>
            </div>
        </section>
    )
}