import Head from 'next/head'
import styles from '../styles/modules/Home.module.css'
import Link from "next/link";

export default function Home() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Link href="/buscador-ingredientes">
                <a>Buscador de ingredientes</a>
            </Link>
        </>
    )    
}