import Head from "next/head";
import { removeAccents } from "../../utils/strings";
import { fetchExcel } from "../api/excel";

export default function buscadorIngredientes({ ingredients }) {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <input type="text" className="search-input" placeholder="¿Mi perro puede comer ..." onKeyUp={(e) => displayMatches(e.target.value)} onChange={(e) => displayMatches(e.target.value)} />
                <div className="suggestions"></div>
            </div>
        </>
    )

    function findMatches(letters) {
        return ingredients.filter(ingredient => {
            const regex = new RegExp(removeAccents(letters), 'gi');
            if (letters != "") {
                return removeAccents(ingredient.name).match(regex);
            }
            return "";
        })
    }

    function displayMatches(letters) {
        const matchArray = findMatches(letters);
        const suggestions = matchArray.map(ingredient => {

            const regex = new RegExp(removeAccents(letters), 'gi');
            const ingrMatched = removeAccents(ingredient.name)
                .replace(regex, `<span style="background-color: yellow">${letters}</span>`)

            return `<li><span class="name">${ingrMatched}</span></li>`;
        }).join('');

        document.querySelector(".suggestions").innerHTML = suggestions;
    }

}

export async function getServerSideProps() {
    let ingredients = await fetchExcel();
    return {
        props: { ingredients }
    }
}